requires 'HTTP::Request';
requires 'JSON::XS';
requires 'LWP::Protocol::https';
requires 'LWP::UserAgent';
requires 'Mojolicious::Lite';
requires 'Readonly';
requires 'Test::Most';
requires 'Try::Tiny';
